spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tarot
    username: yale
    password: 12345
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8080