spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tarot
    username: yale
    password: 12345
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    user:
      name: yale
      password: 12345
      roles: ADMIN
server:
  port: 8080


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true